# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1230, 884)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonSend_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSend_1.setGeometry(QtCore.QRect(1120, 412, 75, 23))
        self.pushButtonSend_1.setObjectName("pushButtonSend_1")
        self.lineEditWrite_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditWrite_1.setGeometry(QtCore.QRect(950, 412, 161, 20))
        self.lineEditWrite_1.setObjectName("lineEditWrite_1")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(910, 342, 121, 20))
        self.label.setObjectName("label")
        self.lineEditResponse = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditResponse.setGeometry(QtCore.QRect(1020, 342, 201, 20))
        self.lineEditResponse.setReadOnly(True)
        self.lineEditResponse.setObjectName("lineEditResponse")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(950, 392, 241, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.lineEditWrite_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditWrite_2.setGeometry(QtCore.QRect(950, 452, 161, 20))
        self.lineEditWrite_2.setObjectName("lineEditWrite_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(950, 432, 241, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.pushButtonSend_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSend_2.setGeometry(QtCore.QRect(1120, 452, 75, 23))
        self.pushButtonSend_2.setObjectName("pushButtonSend_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-100, 730, 1371, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 743, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.logsBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.logsBrowser.setGeometry(QtCore.QRect(10, 770, 1201, 71))
        self.logsBrowser.setObjectName("logsBrowser")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(530, 10, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(990, 372, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(-30, 250, 1381, 71))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(260, 30, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(820, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(90, 50, 191, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(90, 110, 211, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(90, 160, 211, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(90, 220, 251, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(310, 50, 251, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(620, 50, 221, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(620, 110, 191, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(620, 170, 231, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(620, 230, 231, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(880, 50, 201, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(880, 110, 281, 16))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(880, 170, 221, 16))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(880, 230, 231, 16))
        self.label_22.setObjectName("label_22")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(590, 30, 20, 255))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.lineEditWrite_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditWrite_3.setGeometry(QtCore.QRect(950, 502, 161, 20))
        self.lineEditWrite_3.setObjectName("lineEditWrite_3")
        self.pushButtonSend_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSend_3.setGeometry(QtCore.QRect(1120, 502, 75, 23))
        self.pushButtonSend_3.setObjectName("pushButtonSend_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(950, 482, 241, 16))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.pushButtonSend_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSend_4.setGeometry(QtCore.QRect(1120, 542, 75, 23))
        self.pushButtonSend_4.setObjectName("pushButtonSend_4")
        self.lineEditWrite_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditWrite_4.setGeometry(QtCore.QRect(950, 542, 161, 20))
        self.lineEditWrite_4.setObjectName("lineEditWrite_4")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(950, 522, 241, 20))
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.lineEditWrite_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditWrite_5.setGeometry(QtCore.QRect(950, 582, 161, 20))
        self.lineEditWrite_5.setObjectName("lineEditWrite_5")
        self.pushButtonSend_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSend_5.setGeometry(QtCore.QRect(1120, 582, 75, 23))
        self.pushButtonSend_5.setObjectName("pushButtonSend_5")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(950, 602, 241, 20))
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.pushButtonSend_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSend_6.setGeometry(QtCore.QRect(1120, 622, 75, 23))
        self.pushButtonSend_6.setObjectName("pushButtonSend_6")
        self.lineEditWrite_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditWrite_6.setGeometry(QtCore.QRect(950, 622, 161, 20))
        self.lineEditWrite_6.setObjectName("lineEditWrite_6")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(950, 562, 217, 16))
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.pushButtonSend_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSend_7.setGeometry(QtCore.QRect(1120, 672, 75, 23))
        self.pushButtonSend_7.setObjectName("pushButtonSend_7")
        self.lineEditWrite_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditWrite_7.setGeometry(QtCore.QRect(950, 672, 161, 20))
        self.lineEditWrite_7.setObjectName("lineEditWrite_7")
        self.lineEditWrite_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditWrite_8.setGeometry(QtCore.QRect(950, 712, 161, 20))
        self.lineEditWrite_8.setObjectName("lineEditWrite_8")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(950, 652, 241, 16))
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(950, 692, 241, 20))
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.pushButtonSend_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSend_8.setGeometry(QtCore.QRect(1120, 712, 75, 23))
        self.pushButtonSend_8.setObjectName("pushButtonSend_8")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(900, 360, 331, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(890, 284, 20, 455))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.lineEditValue_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditValue_1.setGeometry(QtCore.QRect(90, 70, 191, 21))
        self.lineEditValue_1.setReadOnly(True)
        self.lineEditValue_1.setObjectName("lineEditValue_1")
        self.lineEditValue_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditValue_2.setGeometry(QtCore.QRect(90, 130, 191, 21))
        self.lineEditValue_2.setReadOnly(True)
        self.lineEditValue_2.setObjectName("lineEditValue_2")
        self.lineEditValue_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditValue_3.setGeometry(QtCore.QRect(90, 180, 191, 21))
        self.lineEditValue_3.setReadOnly(True)
        self.lineEditValue_3.setObjectName("lineEditValue_3")
        self.lineEditValue_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditValue_4.setGeometry(QtCore.QRect(90, 240, 191, 21))
        self.lineEditValue_4.setReadOnly(True)
        self.lineEditValue_4.setObjectName("lineEditValue_4")
        self.lineEditValue_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditValue_5.setGeometry(QtCore.QRect(310, 70, 191, 21))
        self.lineEditValue_5.setReadOnly(True)
        self.lineEditValue_5.setObjectName("lineEditValue_5")
        self.lineEditValue_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditValue_6.setGeometry(QtCore.QRect(620, 70, 191, 21))
        self.lineEditValue_6.setReadOnly(True)
        self.lineEditValue_6.setObjectName("lineEditValue_6")
        self.lineEditValue_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditValue_7.setGeometry(QtCore.QRect(620, 130, 191, 21))
        self.lineEditValue_7.setReadOnly(True)
        self.lineEditValue_7.setObjectName("lineEditValue_7")
        self.lineEditValue_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditValue_8.setGeometry(QtCore.QRect(620, 190, 191, 21))
        self.lineEditValue_8.setReadOnly(True)
        self.lineEditValue_8.setObjectName("lineEditValue_8")
        self.lineEditValue_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditValue_9.setGeometry(QtCore.QRect(620, 250, 191, 21))
        self.lineEditValue_9.setReadOnly(True)
        self.lineEditValue_9.setObjectName("lineEditValue_9")
        self.lineEditValue_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditValue_10.setGeometry(QtCore.QRect(880, 70, 191, 21))
        self.lineEditValue_10.setReadOnly(True)
        self.lineEditValue_10.setObjectName("lineEditValue_10")
        self.lineEditValue_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditValue_11.setGeometry(QtCore.QRect(880, 130, 191, 21))
        self.lineEditValue_11.setReadOnly(True)
        self.lineEditValue_11.setObjectName("lineEditValue_11")
        self.lineEditValue_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditValue_12.setGeometry(QtCore.QRect(880, 190, 191, 21))
        self.lineEditValue_12.setReadOnly(True)
        self.lineEditValue_12.setObjectName("lineEditValue_12")
        self.lineEditValue_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditValue_13.setGeometry(QtCore.QRect(880, 250, 191, 21))
        self.lineEditValue_13.setReadOnly(True)
        self.lineEditValue_13.setObjectName("lineEditValue_13")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setEnabled(True)
        self.label_28.setGeometry(QtCore.QRect(50, 330, 771, 391))
        self.label_28.setText("")
        self.label_28.setPixmap(QtGui.QPixmap("schemat.png"))
        self.label_28.setScaledContents(True)
        self.label_28.setObjectName("label_28")
        self.label_b_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_b_3.setGeometry(QtCore.QRect(469, 529, 23, 15))
        self.label_b_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_b_3.setObjectName("label_b_3")
        self.label_b_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_b_4.setGeometry(QtCore.QRect(213, 451, 23, 15))
        self.label_b_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_b_4.setObjectName("label_b_4")
        self.label_b_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_b_5.setGeometry(QtCore.QRect(596, 350, 23, 15))
        self.label_b_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_b_5.setObjectName("label_b_5")
        self.label_b_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_b_11.setGeometry(QtCore.QRect(433, 541, 23, 15))
        self.label_b_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_b_11.setObjectName("label_b_11")
        self.label_b_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_b_12.setGeometry(QtCore.QRect(610, 481, 23, 15))
        self.label_b_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_b_12.setObjectName("label_b_12")
        self.label_b_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_b_13.setGeometry(QtCore.QRect(358, 382, 23, 15))
        self.label_b_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_b_13.setObjectName("label_b_13")
        self.label_f_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_f_1.setGeometry(QtCore.QRect(90, 547, 41, 16))
        self.label_f_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_f_1.setObjectName("label_f_1")
        self.label_f_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_f_2.setGeometry(QtCore.QRect(620, 448, 41, 16))
        self.label_f_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_f_2.setObjectName("label_f_2")
        self.label_bj_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_bj_6.setGeometry(QtCore.QRect(388, 556, 41, 16))
        self.label_bj_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_bj_6.setObjectName("label_bj_6")
        self.label_bj_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_bj_7.setGeometry(QtCore.QRect(539, 554, 41, 16))
        self.label_bj_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_bj_7.setObjectName("label_bj_7")
        self.label_bj_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_bj_8.setGeometry(QtCore.QRect(160, 540, 41, 16))
        self.label_bj_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_bj_8.setObjectName("label_bj_8")
        self.label_bj_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_bj_9.setGeometry(QtCore.QRect(159, 374, 41, 16))
        self.label_bj_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_bj_9.setObjectName("label_bj_9")
        self.label_bj_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_bj_10.setGeometry(QtCore.QRect(270, 440, 41, 16))
        self.label_bj_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_bj_10.setObjectName("label_bj_10")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(910, 290, 121, 20))
        self.label_29.setObjectName("label_29")
        self.pushButtonSave_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSave_1.setGeometry(QtCore.QRect(1150, 290, 75, 23))
        self.pushButtonSave_1.setObjectName("pushButtonSave_1")
        self.lineEditSave_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditSave_1.setGeometry(QtCore.QRect(1020, 290, 121, 20))
        self.lineEditSave_1.setObjectName("lineEditSave_1")
        self.pushButtonSave_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSave_2.setGeometry(QtCore.QRect(1150, 316, 75, 23))
        self.pushButtonSave_2.setObjectName("pushButtonSave_2")
        self.lineEditSave_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditSave_2.setGeometry(QtCore.QRect(1020, 316, 121, 20))
        self.lineEditSave_2.setObjectName("lineEditSave_2")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(910, 316, 121, 20))
        self.label_30.setObjectName("label_30")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1230, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonSend_1.setText(_translate("MainWindow", "Wyślij"))
        self.label.setText(_translate("MainWindow", "Ostatnia odpowiedz:"))
        self.label_2.setText(_translate("MainWindow", "Siłownik zaworu nagrzewnicy wstępnej [%]"))
        self.label_4.setText(_translate("MainWindow", "Siłownik zaworu chłodnicy [%]"))
        self.pushButtonSend_2.setText(_translate("MainWindow", "Wyślij"))
        self.label_5.setText(_translate("MainWindow", "LOGS"))
        self.logsBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">!PROGRAM START!</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "AKTUALNE STANY"))
        self.label_7.setText(_translate("MainWindow", "ZMIEN STAN WYJŚĆ"))
        self.label_8.setText(_translate("MainWindow", "WEJSCIA"))
        self.label_9.setText(_translate("MainWindow", "WYJSCIA"))
        self.label_10.setText(_translate("MainWindow", "Czujnik temp. zewnetrznej [C]"))
        self.label_11.setText(_translate("MainWindow", "Czujnik temp. powietrza wywiewanego [C]"))
        self.label_12.setText(_translate("MainWindow", "Termostat p-zamr. nagrzewnicy [true/false]"))
        self.label_13.setText(_translate("MainWindow", "Prostat filtra podstawowego nawiewu [true/false]"))
        self.label_14.setText(_translate("MainWindow", "Prostat filtra podstawowego wywiewu [true/false]"))
        self.label_15.setText(_translate("MainWindow", "Siłownik zaworu nagrzewnicy wstępnej [%]"))
        self.label_16.setText(_translate("MainWindow", "Siłownik zaworu chłodnicy [%]"))
        self.label_17.setText(_translate("MainWindow", "Prędkość obrotowa wentylatora nawieru [%]"))
        self.label_18.setText(_translate("MainWindow", "Prędkość obrotowa wentylatora wywieru [%] "))
        self.label_19.setText(_translate("MainWindow", "Recylkulacja [%]"))
        self.label_20.setText(_translate("MainWindow", "Załączenie pompy nagrzewnicy wstępnej  [true/false]"))
        self.label_21.setText(_translate("MainWindow", "Załączenie wentylatora nawiewu [true/false]"))
        self.label_22.setText(_translate("MainWindow", "Załączenie wentylatora wywieru [true/talse]"))
        self.pushButtonSend_3.setText(_translate("MainWindow", "Wyślij"))
        self.label_3.setText(_translate("MainWindow", "Predkość obrotowa wentylatora nawiewu [%]"))
        self.pushButtonSend_4.setText(_translate("MainWindow", "Wyślij"))
        self.label_23.setText(_translate("MainWindow", "Predkość obrotowa wentylatora wywiewu [%]"))
        self.pushButtonSend_5.setText(_translate("MainWindow", "Wyślij"))
        self.label_24.setText(_translate("MainWindow", "Załączenie pompy nagrzewnicy wstępnej 0-1"))
        self.pushButtonSend_6.setText(_translate("MainWindow", "Wyślij"))
        self.label_25.setText(_translate("MainWindow", "Recyrkulacja [%]"))
        self.pushButtonSend_7.setText(_translate("MainWindow", "Wyślij"))
        self.label_26.setText(_translate("MainWindow", "Załączenie wentylatora nawiewu 0-1"))
        self.label_27.setText(_translate("MainWindow", "Załączenie wentylatora wywiewu 0-1"))
        self.pushButtonSend_8.setText(_translate("MainWindow", "Wyślij"))
        self.lineEditValue_1.setText(_translate("MainWindow", "UNKNOWN"))
        self.lineEditValue_2.setText(_translate("MainWindow", "UNKNOWN"))
        self.lineEditValue_3.setText(_translate("MainWindow", "UNKNOWN"))
        self.lineEditValue_4.setText(_translate("MainWindow", "UNKNOWN"))
        self.lineEditValue_5.setText(_translate("MainWindow", "UNKNOWN"))
        self.lineEditValue_6.setText(_translate("MainWindow", "UNKNOWN"))
        self.lineEditValue_7.setText(_translate("MainWindow", "UNKNOWN"))
        self.lineEditValue_8.setText(_translate("MainWindow", "UNKNOWN"))
        self.lineEditValue_9.setText(_translate("MainWindow", "UNKNOWN"))
        self.lineEditValue_10.setText(_translate("MainWindow", "UNKNOWN"))
        self.lineEditValue_11.setText(_translate("MainWindow", "UNKNOWN"))
        self.lineEditValue_12.setText(_translate("MainWindow", "UNKNOWN"))
        self.lineEditValue_13.setText(_translate("MainWindow", "UNKNOWN"))
        self.label_b_3.setText(_translate("MainWindow", "X"))
        self.label_b_4.setText(_translate("MainWindow", "X"))
        self.label_b_5.setText(_translate("MainWindow", "X"))
        self.label_b_11.setText(_translate("MainWindow", "X"))
        self.label_b_12.setText(_translate("MainWindow", "X"))
        self.label_b_13.setText(_translate("MainWindow", "X"))
        self.label_f_1.setText(_translate("MainWindow", "X"))
        self.label_f_2.setText(_translate("MainWindow", "X"))
        self.label_bj_6.setText(_translate("MainWindow", "X"))
        self.label_bj_7.setText(_translate("MainWindow", "X"))
        self.label_bj_8.setText(_translate("MainWindow", "X"))
        self.label_bj_9.setText(_translate("MainWindow", "X"))
        self.label_bj_10.setText(_translate("MainWindow", "X"))
        self.label_29.setText(_translate("MainWindow", "Adres Sterownika:"))
        self.pushButtonSave_1.setText(_translate("MainWindow", "Zapisz"))
        self.pushButtonSave_2.setText(_translate("MainWindow", "Zapisz"))
        self.label_30.setText(_translate("MainWindow", "Port COM:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
